# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "irs_forms"
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Ryan Winograd"]
  s.date = "2013-01-09"
  s.description = "Generate IRS forms with your data"
  s.email = "ryan@thewinograds.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "lib/irs_forms.rb",
    "lib/irs_forms/form.rb",
    "lib/irs_forms/form1096.rb",
    "lib/irs_forms/form1099.rb",
    "lib/irs_forms/form1099_int.rb",
    "lib/irs_forms/form1099_misc.rb",
    "spec/assets/copyA_with_data_and_no_template.pdf-0.12.0.pdf",
    "spec/assets/copyA_with_data_and_template.pdf-0.12.0.pdf",
    "spec/assets/copyA_with_template.pdf-0.12.0.pdf",
    "spec/assets/f1096_for_1099int.pdf-0.12.0.pdf",
    "spec/assets/f1096_with_data_and_no_template.pdf-0.12.0.pdf",
    "spec/assets/f1096_with_data_and_template.pdf-0.12.0.pdf",
    "spec/assets/f1096_with_template.pdf-0.12.0.pdf",
    "spec/assets/f1099intA_data_and_template.pdf-0.12.0.pdf",
    "spec/assets/f1099intB_data_and_template.pdf-0.12.0.pdf",
    "spec/assets/f1099intC_data_and_template.pdf-0.12.0.pdf",
    "spec/assets/f1099msc1_data_and_template.pdf-0.12.0.pdf",
    "spec/assets/f1099msc2_data_and_template.pdf-0.12.0.pdf",
    "spec/assets/f1099mscA_data_and_template.pdf-0.12.0.pdf",
    "spec/assets/f1099mscB_data_and_template.pdf-0.12.0.pdf",
    "spec/assets/f1099mscC_data_and_template.pdf-0.12.0.pdf",
    "spec/form1096_spec.rb",
    "spec/form1099_int_spec.rb",
    "spec/form1099_misc_spec.rb",
    "spec/irs_forms_spec.rb",
    "spec/spec_helper.rb",
    "templates/NOTES",
    "templates/f1096--2012.pdf",
    "templates/f1096.pdf",
    "templates/f1099int--2012.pdf",
    "templates/f1099int-copyA.pdf",
    "templates/f1099int-copyB.pdf",
    "templates/f1099int-copyC.pdf",
    "templates/f1099msc--2012.pdf",
    "templates/f1099msc-copy1.pdf",
    "templates/f1099msc-copy2.pdf",
    "templates/f1099msc-copyA.pdf",
    "templates/f1099msc-copyB.pdf",
    "templates/f1099msc-copyC.pdf"
  ]
  s.homepage = "http://github.com/ValencePM/irs_forms"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Generate IRS forms with your data"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_runtime_dependency(%q<prawn>, [">= 0.12.0"])
      s.add_development_dependency(%q<rake>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_development_dependency(%q<appraisal>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_development_dependency(%q<rdoc>, [">= 3.12"])
      s.add_development_dependency(%q<bundler>, [">= 1.0.0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<prawn>, [">= 0.12.0"])
      s.add_dependency(%q<rake>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 1.8.3"])
      s.add_dependency(%q<appraisal>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 2.8.0"])
      s.add_dependency(%q<rdoc>, [">= 3.12"])
      s.add_dependency(%q<bundler>, [">= 1.0.0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<prawn>, [">= 0.12.0"])
    s.add_dependency(%q<rake>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 1.8.3"])
    s.add_dependency(%q<appraisal>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 2.8.0"])
    s.add_dependency(%q<rdoc>, [">= 3.12"])
    s.add_dependency(%q<bundler>, [">= 1.0.0"])
  end
end
